import Footer from "./Components/Footer/Footer"
import Header from "./Components/Header/Header"
import Home from "./Components/Home/Home"


function App() {
  return (
    <>
    </>
  )
}

export default App

//WHEN WE ARE USING REACT-ROUTER DOM THERE IS NO NEED OF APP.JSX. WE CAN DO DIRECTLY
//1.GO TO MAIN.JSX ,REMOVE APP RENDER AND INSERT ROUTER PROVIDER
//2.THIS ROUTER PROVIDER TAKES PROP FOR WORKING,IT NEEDS ONLY ONE THING WHICH IS ROUTER={ROUTER},
//3.WE DIDN'T HAVE MADE ROUTER ,NOW WE LEARN TO MAKE ROUTER,THERE IS A TWO WAY OF MAKING IT

//FIRST WAY
//1. FOR MAKING THE ROUTER IMPORT CREATEBROWSERROUTER([]),IT'S A METHOD WHICH HAS A ARRAY
//2. CREATE A PATH "/" WHICH IS A TOP LEVEL ELEMENT,THE NESTING IS OCCURING INSIDE
//3.MAKE ANOTHER FILE LAYOUT.JSX ,IMPORT HEADER AND FOOTER WHICH IS SAME ,NOW IMPORT OUTLET,WHERE WE WRITE OUTLET WE CAN CHANGE DYNAMICALLY
//4. WE CANNOT MAKE ANYWHERE, WE HAVE TO TELL INDEX FILE WE ARE USING LAYOUT,GIVING EVERYTHING INSIDE IT
//5 NOW WE HAVE TO TELL CREATEBROWSERROUTER([]) WHAT IT CAN RENDER ,ELEMENT:<LAYOUT/>>
//6. WE CAN ALSO ADD CHILDREN BECAUSE WE HAVE FURTHER MORE VALUES ,CHILDREN=[{},{}],JITNI NESTING KRNI UTNE OBJECT,OBJECT HAS PATH AND ELEMENT AS ABOVE

//SECOND WAY IS DEFINED IN MAIN.JSX
